# Generated by Django 5.1.4 on 2025-03-08 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0004_empleado_dcargo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='dpi',
            new_name='tel',
        ),
        migrations.RemoveField(
            model_name='configuraciongeneral',
            name='logotipo2',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='dcargo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='dcargo2',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipoc',
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='correo',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='sitio_web',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='tel',
            field=models.CharField(default=2315465, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados_app.grado'),
        ),
    ]
