# Generated by Django 5.1.4 on 2025-03-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0005_grado_rename_dpi_empleado_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
