# Generated by Django 5.1.4 on 2025-03-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0006_alter_grado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tel',
            field=models.CharField(max_length=15),
        ),
    ]
