# Generated by Django 5.1.4 on 2025-03-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0007_alter_empleado_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='nombre_institucion2',
            field=models.CharField(default=2, max_length=255, verbose_name='Nombre de la Institución2'),
            preserve_default=False,
        ),
    ]
