# Generated by Django 5.1.4 on 2025-03-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0008_configuraciongeneral_nombre_institucion2'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='descripcion',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
