# Generated by Django 5.1.4 on 2025-03-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0011_alter_grado_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='descripcion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
