# Generated by Django 5.1.4 on 2025-03-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0012_alter_grado_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='qr_code',
        ),
    ]
