# Generated by Django 5.1.4 on 2025-03-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0013_remove_empleado_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
