# Generated by Django 5.1.4 on 2026-02-25 02:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados_app", "0014_alter_grado_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["establecimiento__nombre", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Establecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=160, unique=True)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                (
                    "background_gafete",
                    models.ImageField(blank=True, null=True, upload_to="logotipos2/"),
                ),
                (
                    "gafete_ancho",
                    models.PositiveIntegerField(
                        default=880,
                        validators=[
                            django.core.validators.MinValueValidator(500),
                            django.core.validators.MaxValueValidator(1800),
                        ],
                    ),
                ),
                (
                    "gafete_alto",
                    models.PositiveIntegerField(
                        default=565,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(1200),
                        ],
                    ),
                ),
                ("gafete_layout_json", models.JSONField(blank=True, default=dict)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="empleado",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="grado",
            options={"ordering": ["nombre"]},
        ),
        migrations.AddField(
            model_name="empleado",
            name="codigo_personal",
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="cui",
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grado",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="grado",
            name="jornada",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="grado",
            name="seccion",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="grado",
            name="carrera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grados",
                to="empleados_app.carrera",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="establecimiento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carreras",
                to="empleados_app.establecimiento",
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="establecimiento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alumnos",
                to="empleados_app.establecimiento",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="carrera",
            unique_together={("establecimiento", "nombre")},
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ciclo",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2200),
                        ]
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="activo",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="empleados_app.empleado",
                    ),
                ),
                (
                    "grado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="empleados_app.grado",
                    ),
                ),
            ],
            options={
                "ordering": ["-ciclo", "alumno__apellidos", "alumno__nombres"],
                "unique_together": {("alumno", "grado", "ciclo")},
            },
        ),
    ]
