# Generated by Django 5.1.4 on 2026-02-25 02:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados_app", "0014_alter_grado_descripcion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=180)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["establecimiento__nombre", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Establecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=180, unique=True)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                (
                    "fondo_gafete",
                    models.ImageField(blank=True, null=True, upload_to="logotipos2/"),
                ),
                (
                    "gafete_ancho",
                    models.PositiveIntegerField(
                        default=1012,
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(3000),
                        ],
                    ),
                ),
                (
                    "gafete_alto",
                    models.PositiveIntegerField(
                        default=638,
                        validators=[
                            django.core.validators.MinValueValidator(180),
                            django.core.validators.MaxValueValidator(2200),
                        ],
                    ),
                ),
                ("gafete_capas", models.JSONField(default=list)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Establecimiento",
                "verbose_name_plural": "Establecimientos",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="grado",
            options={"ordering": ["nombre"]},
        ),
        migrations.AddField(
            model_name="grado",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="grado",
            name="jornada",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="grado",
            name="seccion",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RenameModel(
            old_name="Empleado",
            new_name="Alumno",
        ),
        migrations.AlterModelOptions(
            name="alumno",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="alumno",
            name="codigo_personal",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="alumno",
            name="cui",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="alumno",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alumnos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grado",
            name="carrera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grados",
                to="empleados_app.carrera",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="establecimiento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carreras",
                to="empleados_app.establecimiento",
            ),
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ciclo",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2200),
                        ]
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="empleados_app.alumno",
                    ),
                ),
                (
                    "grado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="empleados_app.grado",
                    ),
                ),
            ],
            options={
                "ordering": ["-ciclo", "alumno__apellidos"],
                "unique_together": {("alumno", "grado", "ciclo")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="carrera",
            unique_together={("establecimiento", "nombre")},
        ),
    ]
