# Generated by Django 5.1.4 on 2026-02-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "empleados_app",
            "0015_carrera_establecimiento_alter_empleado_options_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_name = 'empleados_app_empleado'
                ) AND NOT EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_name = 'empleados_app_alumno'
                ) THEN
                    ALTER TABLE empleados_app_empleado RENAME TO empleados_app_alumno;
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_name = 'empleados_app_alumno'
                ) AND NOT EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_name = 'empleados_app_empleado'
                ) THEN
                    ALTER TABLE empleados_app_alumno RENAME TO empleados_app_empleado;
                END IF;
            END
            $$;
            """,
        ),
    ]
