# Generated by Django 5.1.4 on 2026-02-25 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados_app", "0017_cicloescolar_and_matricula_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matricula",
            options={
                "ordering": ["-created_at", "alumno__apellidos", "alumno__nombres"]
            },
        ),
        migrations.RenameIndex(
            model_name="cicloescolar",
            new_name="empleados_a_estable_ff9faa_idx",
            old_name="empleados_ap_estable_70f9a0_idx",
        ),
        migrations.RenameIndex(
            model_name="cicloescolar",
            new_name="empleados_a_estable_c5f9ce_idx",
            old_name="empleados_ap_estable_a4b786_idx",
        ),
        migrations.RenameIndex(
            model_name="matricula",
            new_name="empleados_a_grado_i_0df73d_idx",
            old_name="empleados_ap_grado_958691_idx",
        ),
        migrations.RenameIndex(
            model_name="matricula",
            new_name="empleados_a_grado_i_19e6a3_idx",
            old_name="empleados_ap_grado_aef92f_idx",
        ),
        migrations.AlterField(
            model_name="matricula",
            name="ciclo",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2200),
                ],
            ),
        ),
    ]
