# Generated by Django 5.1.4 on 2026-02-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados_app", "0021_establecimiento_sitio_web"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="tel",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
